# Generated by Django 3.2.12 on 2022-03-16 02:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obtained_date', models.DateField(blank=True, null=True)),
                ('made_by', models.CharField(blank=True, max_length=400, null=True)),
                ('SMILES', models.TextField(blank=True, max_length=4000, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(blank=True, max_length=400, null=True)),
                ('special_memo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, null=True, to='ion_manager.Tag')),
            ],
            options={
                'verbose_name': 'Chemical',
            },
        ),
    ]
