# Generated by Django 3.2.12 on 2022-03-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ion_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='special_memo',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
