# Generated by Django 3.2.12 on 2022-03-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ion_manager', '0002_alter_chemical_special_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
