# Generated by Django 3.2.12 on 2022-03-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ion_manager', '0003_chemical_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='Mn',
            field=models.FloatField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='Mw',
            field=models.FloatField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='MwMn',
            field=models.FloatField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='mol_ratio',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='wt_ratio',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
