# Generated by Django 3.2.12 on 2022-03-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ion_manager', '0004_auto_20220316_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='Polymn_deg',
            field=models.FloatField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='Structure',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='Tg',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='melting_temp',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
