# Generated by Django 3.2.12 on 2022-03-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ion_manager', '0005_auto_20220316_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='chemical',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
