# Generated by Django 3.2.12 on 2022-03-16 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ion_manager', '0008_composite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composite',
            options={'verbose_name': 'Composite'},
        ),
        migrations.AddField(
            model_name='composite',
            name='component2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chem_component2', to='ion_manager.chemical'),
        ),
        migrations.AddField(
            model_name='composite',
            name='component3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chem_component3', to='ion_manager.chemical'),
        ),
        migrations.AddField(
            model_name='composite',
            name='component4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chem_component4', to='ion_manager.chemical'),
        ),
        migrations.AddField(
            model_name='composite',
            name='component5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chem_component5', to='ion_manager.chemical'),
        ),
        migrations.AddField(
            model_name='composite',
            name='component6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chem_component6', to='ion_manager.chemical'),
        ),
        migrations.AlterField(
            model_name='composite',
            name='component1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chem_component1', to='ion_manager.chemical'),
        ),
    ]
