# Generated by Django 3.2.12 on 2022-03-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ion_manager', '0009_auto_20220316_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composite',
            old_name='ionorg_name',
            new_name='inorg_name',
        ),
    ]
